import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillInstagram,
  AiFillFacebook,
  AiFillGithub,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import angga from "../public/angga.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portofolio Angga Sulistiangga</title>
        <meta name="description" content="Generated by Portofolio Angga Sulistiangga" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">GoldenLion.</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/19cE2yDxZhGTfMEybvFG0QoFhItnKqTrN/view?usp=sharing"
                >
                  RESUME
                </a>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/1kh5lpua5-QoowWM5mj-T78aG7JngJF6D/view?usp=sharing"
                >
                  CV
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Angga Sulistiangga
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Software and Cloud Engineer: Crafting Digital Excellence.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Freelancer providing services for programming and design content needs in application.
              Join me down below and let&apos;s get cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.facebook.com/angganax.barat"><AiFillFacebook /></a>
              <a href="https://www.linkedin.com/in/sulistiangga/"><AiFillLinkedin /></a>
              <a href="https://www.instagram.com/panggilgaaaja/"><AiFillInstagram /></a>
              <a href="https://github.com/Sulistiangga56"><AiFillGithub /></a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={angga} alt="Foto Profil Angga Sulistiangga" layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white text-center">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            I am Angga Sulistiangga, a diligent and dedicated individual with a passion for using technology to make the world a better place.
            I always strive to improve my skills and abilities, and I am determined to give my best effort in everything I do. 
            I was drawn to this field and have since dedicated myself to learning as much as possible. I am excited about the opportunity to apply my skills and dedication.
            A dedicated student pursuing a degree in Information Technology (IT) with expertise in Cloud Computing, Network Infrastructure, Software Development, and Data Engineering. 
            Possessing an educational background in Computer Engineering and practical experience in designing, implementing, and managing cloud infrastructure, as well as building innovative and interactive software solutions. 
            Strong leadership and integrity skills, with the ability to work collaboratively within a team.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              <span className="text-teal-500">Embrace the possibilities, believe in something extraordinary!</span>
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} alt="design" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Elegant Software Design
              </h3>
              <p className="py-2">
                Crafting beautiful and efficient software designs that align with core principles and design theories.
              </p>
              <h4 className="py-4 text-teal-600">Tools and Technologies</h4>
              <p className="text-gray-800 py-1">UML Diagrams</p>
              <p className="text-gray-800 py-1">Design Patterns</p>
              <p className="text-gray-800 py-1">User-Centered Design</p>
              <p className="text-gray-800 py-1">Etc.</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} alt="code" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Code Your Vision
              </h3>
              <p className="py-2">
                Have a groundbreaking software project in mind? Let&apos;s transform your ideas into reality through expert coding.
              </p>
              <h4 className="py-4 text-teal-600">Development Tools</h4>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">PHP</p>
              <p className="text-gray-800 py-1">Cloud Platforms</p>
              <p className="text-gray-800 py-1">Etc.</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} alt="consulting" width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consulting Website or Cloud</h3>
              <p className="py-2">
                Are you interested in optimizing and feedback for your current or cloud project? I can
                give you tips and tricks to level it up.
              </p>
              <h4 className="py-4 text-teal-600">Cloud and Deployment Expertise</h4>
              <p className="text-gray-800 py-1">AWS</p>
              <p className="text-gray-800 py-1">Azure</p>
              <p className="text-gray-800 py-1">Google Cloud</p>
              <p className="text-gray-800 py-1">Etc.</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white text-center">My Project</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Throughout my journey in the field of technology, particularly as a Software Engineer and Cloud Specialist,
              I&apos;ve had the privilege of working on a variety of remarkable projects.
              From designing scalable cloud solutions to developing cutting-edge software applications,
              my journey has been characterized by collaboration, innovation, and a passion for technology.
              I can also be described as a Full Stack Engineer while working on certain projects.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I offer a comprehensive range of services, including cloud infrastructure design, software development,
              and knowledge sharing. Whether it&apos;s optimizing cloud resources, building robust applications, or
              imparting insights through teaching, I am committed to delivering excellence in every project.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Explore the highlights of my journey below, showcasing the fusion of software engineering and cloud 
            expertise to create impactful digital solutions for businesses and individuals alike.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <a href="https://github.com/travel-yours"><Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
                alt="travelyours"
              /></a>
              <h3 className="text-3xl py-1 dark:text-white text-center" >TravelYours</h3>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://github.com/Sulistiangga56/Project_PengmasUMKM"><Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
                alt="iwapi"
              /></a>
              <h3 className="text-3xl py-1 dark:text-white text-center" >Iwapi UMKM</h3>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://github.com/Sulistiangga56/PenjadwalanPerkuliahan"><Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
                alt="penjadwalan"
              /></a>
              <h3 className="text-3xl py-1 dark:text-white text-center" >Lecture Scheduling</h3>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://github.com/Sulistiangga56/Bus_Firebase"><Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
                alt="aplikasi bus"
              /></a>
              <h3 className="text-3xl py-1 dark:text-white text-center" >Application Bus</h3>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://github.com/Sulistiangga56/SQLinjection"><Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
                alt="sql injection"
              /></a>
              <h3 className="text-3xl py-1 dark:text-white text-center" >SQL Injection</h3>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://github.com/Sulistiangga56/InventoryGudang"><Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
                alt="inventory gudang"
              /></a>
              <h3 className="text-3xl py-1 dark:text-white text-center" >Warehouse Inventory</h3>
            </div>
            <div className="basis-1/3 flex-1">
            <a href="https://github.com/Sulistiangga56?tab=repositories"><h3 className="text-3xl py-1 dark:text-white text-center mx-auto bg-gradient-to-b from-teal-500 rounded-full overflow-hidden" >More...</h3></a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
